info:
  component: API-GATEWAY

server:
  port: 10001

security:
  sessions: NEVER
management:
  security:
    enabled: false
spring:
  redis:
    host: 10.21.21.102
    port: 6379
    password: HuaWei!@#123

#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.68.51.99:8765/eureka/

#logging.level.ROOT: DEBUG


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


zuul:
  sensitiveHeaders:
  routes:
    test:
        path: /test/**
        stripPrefix: false
        serviceId: test