info:
  component: API-GATEWAY

server:
  port: 10001

security:
  sessions: NEVER
management:
  security:
    enabled: false

spring:
  redis:
    host: 10.68.51.99
    port: 6379
    #password: HuaWei!@#123
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.68.51.99:3300/exposure
    username: root
    password: 123456

#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.68.51.99:8765/eureka/

#logging.level.ROOT: DEBUG


ribbon: 
  ReadTimeout: 60000
  MaxAutoRetries: 1
  
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


zuul:
  sslHostnameValidationEnabled: false
  sensitiveHeaders:
  routes:
    gateway:
        path: /gw/**
        stripPrefix: true
        url: https://10.21.152.240/
    test:
        path: /test/**
        stripPrefix: false
        serviceId: test
    basisSettingWatch:
        path: /im/**
        url: https://10.21.29.38/im/